// Sections data for navigation and content structure
export const sections = [
  // Lecture 1&2: Sections 1-15
  { id: "osi-model", title: "OSI Reference Model" },
  { id: "application-layer", title: "Application Layer (Layer 7)" },
  { id: "presentation-layer", title: "Presentation Layer (Layer 6)" },
  { id: "session-layer", title: "Session Layer (Layer 5)" },
  { id: "transport-layer", title: "Transport Layer (Layer 4)" },
  { id: "network-layer", title: "Network Layer (Layer 3)" },
  { id: "datalink-layer", title: "Data Link Layer (Layer 2)" },
  { id: "physical-layer", title: "Physical Layer (Layer 1)" },
  { id: "link-types", title: "Types of Links" },
  { id: "pdu", title: "Protocol Data Unit" },
  { id: "frame-layer2", title: "Frame (Data Link Layer)" },
  { id: "packet-layer3", title: "Packet (Network Layer)" },
  { id: "segment-datagram", title: "Segment & Datagram" },
  { id: "packet-structure", title: "Packet Structure" },
  { id: "ip-addressing", title: "IP Addressing" },
  // Lecture 3,4&5: Sections 16-27
  { id: "network-performance", title: "Network Performance Metrics" },
  { id: "routing-problems", title: "Routing Problems" },
  { id: "need-to-route", title: "The Need to Route" },
  { id: "routers", title: "Routers" },
  { id: "routing-basics", title: "Routing Basics" },
  { id: "routing-tables", title: "Routing Tables" },
  { id: "routing-protocols", title: "Routing Protocols" },
  { id: "router-evaluation", title: "Router Evaluation Criteria" },
  { id: "router-components", title: "Router Components" },
  { id: "router-roles-wan", title: "Router Roles in WANs" },
  { id: "autonomous-systems", title: "Autonomous Systems" },
  { id: "routing-table-deep", title: "Routing Table Details" },
  // Lecture 6&7: Sections 28-32
  { id: "routing-algorithms", title: "Routing Algorithms Overview" },
  { id: "convergence-states", title: "Convergence States" },
  { id: "distance-vector", title: "Distance-Vector Routing Protocol" },
  { id: "link-state", title: "Link-State Routing Protocol" },
  { id: "routing-protocols-comparison", title: "Routing Protocols Comparison" },
];
